version: "3.3"
services:
  wj-redis:
    image: wj_redis
    volumes:
      - "/var/lib/redis:/var/lib/redis"
    restart: always
    networks:
      wj_network:
        ipv4_address: 172.18.0.2

  wj-mysql8:
    image: wj_mysql8
    volumes:
      - "/var/lib/mysql8:/var/lib/mysql"
    restart: always
    networks:
      wj_network:
        ipv4_address: 172.18.0.3

  wj-research:
    image: wj_php72:v1.6
    volumes:
      - "/home/xxx:/home/xxx"
    restart: always
    networks:
      wj_network:
        ipv4_address: 172.18.0.4

  wj-python3:
    image: wj_research_python3:v1.6
    restart: always
    volumes:
      - "/home/xxx:/root/xxx"
    networks:
      wj_network:
        ipv4_address: 172.18.0.6

  wj-openresty:
    image: wj_openresty:v1.6
    volumes:
      - "/home/xxx:/home/xxx"
    ports:
      - "8088:80"
    restart: always
    networks:
      wj_network:
        ipv4_address: 172.18.0.5

networks:
  wj_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.0.0/16
      #- gateway: 172.18.0.1

#volumes:
#  db_redis: "/var/lib/redis"
#  db_mysql: "/var/lib/mysql"
#  data_project: "/home/wwwroot"
#  data_all: "/home/wwwroot"



